djangoCRUD14/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("password_change/", views.password_change, name="password_change"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
]

djangoCRUD14/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )

djangoCRUD14/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )

djangoCRUD14/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_http_methods, require_POST
from django.http import JsonResponse

from django.contrib import messages

# 회원가입 이메일 인증 관련
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage

from .tokens import account_activation_token

# Create your views here.
def index(request):
    users = get_user_model().objects.all().order_by("-id")
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


def detail(request, pk):
    person = get_user_model().objects.get(pk=pk)
    context = {
        "person": person,
    }
    return render(request, "accounts/detail.html", context)


def activateEmail(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string(
        "accounts/template_activate_account.html",
        {
            "user": user.username,
            "domain": get_current_site(request).domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": account_activation_token.make_token(user),
            "protocol": "https" if request.is_secure() else "http",
        },
    )
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(
            request,
            f"Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \
            received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.",
        )
    else:
        messages.error(
            request,
            f"Problem sending confirmation email to {to_email}, check if you typed it correctly.",
        )


def activate(request, uidb64, token):

    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(
            request,
            "Thank you for your email confirmation. Now you can login your account.",
        )
        return redirect("accounts:login")
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect("accounts:index")


def signup(request):
    if request.user.is_authenticated:
        return redirect("accounts:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get("email"))
            return redirect("accounts:index")
        else:
            for err in list(form.errors.values()):
                messages.error(request, err)
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")


def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:index")


def password_change(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password_change.html", context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        User = get_user_model()
        person = User.objects.get(pk=user_pk)
        if person != request.user:  # 프로필 페이지 유저 != 요청을 보낸 유저
            if person.followers.filter(
                pk=request.user.pk
            ).exists():  # 프로필 페이지 유저를 팔로우 하는 목록에, 요청 보낸 유저 아이디 있으면
                person.followers.remove(request.user)  # 팔로우 취소
                is_followed = False

            else:  # 없으면
                person.followers.add(request.user)
                is_followed = True

            context = {
                "is_followed": is_followed,
                "followers_count": person.followers.count(),
                "followings_count": person.followings.count(),
            }
            return JsonResponse(context)
        return redirect("accounts:detail", person.username)
    return redirect("accounts:login")

djangoCRUD14/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h5>유저 번호:
  {{ person.pk }}</h5>
<h1>제목:
  {{ person.username }}</h1>
<h6>이메일:
  {{ person.email }}</h6>
<p>생성 일자:
  {{ person.date_joined }}</p>


{% comment %} 팔로잉 {% endcomment %}
<hr class="mt-5">
<div>
  <div>
    팔로워: <span id="followers-count">{{ person.followers.all|length }}</span> /
    팔로잉: <span id="followings-count">{{ person.followings.all|length }}</span>
  </div>
  {% if request.user != person %}
  <div>
    <form id="follow-form" data-user-id="{{ person.pk }}" class="mt-3">
      {% csrf_token %}
      {% if request.user in person.followers.all %}
        <input type="submit" value="팔로우 취소" class="btn btn-primary">
      {% else %}
        <input type="submit" value="팔로우" class="btn btn-primary">
      {% endif %}
    </form>
  </div>
  {% endif %}
</div>




{% comment %} 좋아요 {% endcomment %}
<hr class="mt-5">
<h4>좋아요 한 게시글:
  {{ person.like_articles.count }}개
</h4>

{% for like_article in person.like_articles.all %}
<h6>
  <a href="{% url 'articles:detail' like_article.pk %}" class="text-decoration-none">{{ like_article.title }}</a>
</h6>
{% endfor %}






{% comment %} 댓글 {% endcomment %}
<hr class="mt-5">
<h4>작성한 댓글:
  {{user.comment_set.count }}개
</h4>

{% for comment in person.comment_set.all %}
<h6>{{ comment.content }}
  -
  <a href="{% url 'articles:detail' comment.article.pk %}" class="text-decoration-none">{{ comment.article.title }}</a>
</h6>
{% endfor %}


{% comment %} 버튼 {% endcomment %}
<hr class="mt-5">
<button class="btn btn-secondary">
  <a href="{% url 'accounts:index' %}" class="text-white text-decoration-none">
    메인
  </a>
</button>
{% if request.user == user %}
<button class="btn btn-primary">
  <a href="{% url 'accounts:update' %}" class="text-white text-decoration-none">
    수정
  </a>
</button>
<button class="btn btn-info">
  <a href="{% url 'accounts:password_change' %}" class="text-white text-decoration-none">
    비밀번호 변경
  </a>
</button>
<button class="btn btn-danger">
  <a href="{% url 'accounts:delete' %}" class="text-white text-decoration-none">
    삭제
  </a>
</button>
{% endif %}

{% endblock body %}

{% block script %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const form = document.querySelector('#follow-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  form.addEventListener('submit', function (event) {
    event.preventDefault()
    const userId = event.target.dataset.userId

    axios({
      method: 'post',
      url: `/accounts/${userId}/follow/`,
      headers: { 'X-CSRFToken': csrftoken, }
    })
      .then((response) => {
        const isFollowed = response.data.is_followed
        const followBtn = document.querySelector('#follow-form > input[type=submit]')
        if (isFollowed === true) {
          followBtn.value = '팔로우 취소'
        } else {
          followBtn.value = '팔로우'
        }
        const followersCountTag = document.querySelector("#followers-count")
        const followingsCountTag = document.querySelector("#followings-count")
        const followersCount = response.data.followers_count
        const followingsCount = response.data.followings_count
        followersCountTag.innerText = followersCount
        followingsCountTag.innerText = followingsCount
      })
      .catch((error) => {
        console.log(error.response)
      })
  })
</script>
{% endblock script %}

djangoCRUD14/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block body %}
  
  <h1>회원 목록</h1>

  {% comment %} 테이블 {% endcomment %}
  <table class="table mt-5">
    <thead class="table-dark">
      <tr>
        <th>글 번호</th>
        <th>이름</th>
        <th>이메일</th>
        <th>생성 일자</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td><a href="{% url 'accounts:detail' user.id %}">{{ user.username }}</a></td>
          <td>{{ user.email }}</td>
          <td>{{ user.date_joined }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock body %}

djangoCRUD14/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>signup</h1>

  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}

djangoCRUD14/accounts/templates/accounts/template_activate_account.html
{% autoescape off %}
  Hi {{ user.username }}, 
  Please click on the link below to confirm your registration: http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

djangoCRUD14/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>update</h1>

  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}