pjt_15/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("<int:pk>/", views.detail, name="detail"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("edit/", views.edit, name="edit"),
    path("password_change/", views.password_change, name="password_change"),
]

pjt_15/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/edit", views.edit, name="edit"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:pk>/comment_create", views.comment_create, name="comment_create"),
]

pjt_15/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pjt_15/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

pjt_15/articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(
        blank=True,
        processors=[Thumbnail(200, 300)],
        format="JPEG",
        options={"quality": 90},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

pjt_15/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )
        labels = {
            "username": "이름",
            "email": "이메일",
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )

pjt_15/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ("user",)
        labels = {
            "title": "제목",
            "content": "내용",
            "image": "이미지",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

pjt_15/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    users = get_user_model().objects.all().order_by("-pk")
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


def signup(request):

    if request.user.is_authenticated:
        return redirect("accounts:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("accounts:index")


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:index")


@login_required
def edit(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/edit.html", context)


@login_required
def password_change(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password_change.html", context)

pjt_15/articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm, CommentForm
from .models import Article
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    articles = Article.objects.all().order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("articles:index")
    else:
        form = ArticleForm()

    context = {
        "form": form,
    }
    return render(request, "articles/create.html", context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    context = {
        "article": article,
        "comments": article.comment_set.all(),
        "comment_form": comment_form,
    }
    return render(request, "articles/detail.html", context)


@login_required
def edit(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        "form": form,
    }
    return render(request, "articles/edit.html", context)


@login_required
def delete(request, pk):
    Article.objects.get(pk=pk).delete()
    return redirect("articles:index")


def comment_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.save()
    return redirect("articles:detail", article.pk)

pjt_15/pjt/views.py
from django.shortcuts import render, redirect


def index(request):
    return render(request, "root.html")

pjt_15/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
  <h1>detail</h1>

  <div class="mt-5">
    <h6>유저 번호:
      {{ user.pk }}</h6>
    <h1>닉네임:
      {{ user.username }}</h1>
    <h6>생성 일자:
      {{ user.date_joined }}</h6>

    {% if user.image %}
      <div class="mt-5">
        <img src="{{ user.image.url }}">
      </div>
    {% endif %}

    <div class="mt-5">
      <p>{{ user.content }}</p>
    </div>

  </div>

  <hr class="mt-5">

  <div class="btn btn-secondary">
    <a href="{% url "accounts:index" %}" class="text-decoration-none text-white">메인</a>
  </div>
  {% if request.user == user %}
    <div class="btn btn-primary">
      <a href="{% url "accounts:edit" %}" class="text-decoration-none text-white">수정</a>
    </div>
    <div class="btn btn-primary opacity-50">
      <a href="{% url "accounts:password_change" %}" class="text-decoration-none text-white">비밀번호 변경</a>
    </div>
    <div class="btn btn-danger">
      <a href="{% url "accounts:delete" %}" class="text-decoration-none text-white">삭제</a>
    </div>
  {% endif %}

{% endblock body %}

pjt_15/accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>edit</h1>
  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}

pjt_15/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>accounts index</h1>

  <table class="table mt-5">
    <thead class="table-dark">
      <tr>
        <td>유저 번호</td>
        <td>이름</td>
        <td>가입 일자</td>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{ user.pk }}</td>
          <td>
            <a href="{% url 'accounts:detail' user.pk %}" class="text-decoration-none">
              {{ user.username }}</a>
          </td>
          <td>{{ user.date_joined }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="d-flex justify-content-end">

    {% if request.user.is_authenticated %}
      <div class="btn btn-danger">
        <a href="{% url 'accounts:logout' %}" class="text-decoration-none text-white">로그아웃</a>
      </div>

    {% else %}
      <div class="btn btn-primary">
        <a href="{% url 'accounts:signup' %}" class="text-decoration-none text-white">회원 가입</a>
      </div>
      <div class="btn btn-success">
        <a href="{% url 'accounts:login' %}" class="text-decoration-none text-white">로그인</a>
      </div>

    {% endif %}
  </div>
{% endblock body %}

pjt_15/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>login</h1>
  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}

pjt_15/accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>password change</h1>
  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}

pjt_15/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}

pjt_15/templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
  </head>

  <body>
    {% comment %} 네비 바 {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:index' %}">회원 목록</a>
              <a class="nav-link" href="{% url 'articles:index' %}">게시글 목록</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled">Disabled</a>
            </div>
          </div>
        </div>
      </nav>

    {% comment %} 메인 {% endcomment %}
    <section class="container mt-5">
      {% block body %}{% endblock body %}
    </section>
  </body>

</html>

pjt_15/templates/root.html
{% extends 'base.html' %}

{% block body %}
  <h1 class="text-center">루트 페이지</h1>

  <div class="d-flex justify-content-evenly mt-5">
    <div class="btn btn-primary">
      <a href="{% url 'accounts:index' %}" class="text-white text-decoration-none">
        회원 목록
      </a>
    </div>
    <div class="btn btn-success">
      <a href="{% url 'articles:index' %}" class="text-white text-decoration-none">
        게시글 목록
      </a>
    </div>
  </div>
{% endblock body %}