djangoCRUD14/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/comment/create/", views.comment_create, name="comment_create"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("search/", views.search, name="search"),
    path("<int:article_pk>/like/", views.like, name="like"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/like",
        views.comment_like,
        name="comment_like",
    ),
]

djangoCRUD14/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_comment_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_comments"
    )

djangoCRUD14/articles/forms.py
from django import forms
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ("user", "like_users")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

djangoCRUD14/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model

# Create your views here.
def index(request):
    articles = Article.objects.all().order_by("-id")
    page = request.GET.get("page")  # 현재 몇 번째 페이지인지
    paginator = Paginator(articles, 10)  # (글 목록, 1페이지에 몇 개씩?)
    page_obj = paginator.get_page(page)  # 몇 번째 페이지 가져올지
    page_range = paginator.page_range

    context = {
        "articles": articles,
        "page_obj": page_obj,
        "page_range": page_range,
    }
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect("articles:index")
    else:
        form = ArticleForm()
    context = {
        "form": form,
    }
    return render(request, "articles/create.html", context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        "article": article,
        "comments": comments,
        "comment_form": comment_form,
    }
    return render(request, "articles/detail.html", context)


@login_required
def delete(request, pk):
    Article.objects.get(pk=pk).delete()
    return redirect("articles:index")


@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        "form": form,
    }
    return render(request, "articles/update.html", context)


@login_required
def comment_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST, request.user)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
    return redirect("articles:detail", article.pk)


@login_required
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect("articles:detail", article_pk)


def search(request):
    search_1 = request.GET.get("search_1")
    search_2 = request.GET.get("search_2")

    if search_1 == "title":
        search_articles = Article.objects.filter(title__icontains=search_2)
    elif search_1 == "content":
        search_articles = Article.objects.filter(content__icontains=search_2)
    elif search_1 == "username":
        search_articles = Article.objects.filter(
            user_id=get_user_model().objects.get(username=search_2)
        )

    page = request.GET.get("page")
    paginator = Paginator(search_articles, 10)
    page_obj = paginator.get_page(page)
    page_range = paginator.page_range

    context = {
        "search_1": search_1,
        "search_2": search_2,
        "search_articles": search_articles,
        "page_obj": page_obj,
        "page_range": page_range,
    }
    return render(request, "articles/search.html", context)


@login_required
def like(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect("articles:detail", article_pk)


@login_required
def comment_like(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user in comment.like_comment_users.all():
        comment.like_comment_users.remove(request.user)
    else:
        comment.like_comment_users.add(request.user)
    return redirect("articles:detail", article_pk)

djangoCRUD14/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>create</h1>
  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}

djangoCRUD14/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h5>글 번호:
    {{ article.pk }}</h5>
  <h1>제목:
    {{ article.title }}</h1>
  <h6>생성 일자:
    {{ article.created_at }}</h6>
  <p>내용:
    {{ article.content }}</p>

  {% comment %} 좋아요 {% endcomment %}
  <div class="mt-5">
    <h3>
      <a href="{% url 'articles:like' article.pk %}" class="text-decoration-none">
        {% if request.user in article.like_users.all %}
          <span><i class="bi bi-hand-thumbs-up-fill"></i></span> 
        {% else %}
          <span><i class="bi bi-hand-thumbs-up"></i></span> 
        {% endif %}
      </a>
        <p class="d-inline">: 
        {% if article.like_users.count == 0 %}
          좋아요를 눌러주세요.
        {% elif article.like_users.count == 1 %}
          {{ article.like_users.all.0 }} 님이 좋아합니다.
        {% else %}
          {{ article.like_users.all.0 }} 외 {{ article.like_users.count |add:-1 }}명</p>
          {{ new_user }}
        {% endif %}
    </h3>
  </div>


  {% comment %} 댓글 {% endcomment %}
  <hr class="mt-5">
  <h3>
    댓글: {{ article.comment_set.count }}개
  </h3>
  
  {% comment %} 댓글 목록 {% endcomment %}
  <div class="mt-5">
  {% for comment in comments %}
    <div class="d-flex justify-content-between">
      <div>
        <p>{{ comment.content }}</p>
        <p>
          <a href="{% url 'accounts:detail' comment.user.pk %}">{{ comment.user }}</a> 
          | {{ comment.created_at }} | 
          <a href="{% url "articles:comment_like" article.pk comment.pk %}" class="text-decoration-none">
            {% if request.user in comment.like_comment_users.all %}
              <span><i class="bi bi-hand-thumbs-up-fill"></i></span>
            {% else %}
              <span><i class="bi bi-hand-thumbs-up"></i></span>
            {% endif %}
          </a>
          : {{ comment.like_comment_users.count }}
        </p>
      </div>
      <div>

        {% comment %} 댓글 수정 {% endcomment %}
        <a href="">수정</a>

        {% comment %} 댓글 삭제 {% endcomment %}
        <!-- 요청과 댓글의 user 일치하면 삭제 -->
        {% if request.user == comment.user %}
          <button type="button" class="btn btn-danger">
            <a href="{% url 'articles:comment_delete' article.pk comment.pk %}" class="text-white text-decoration-none">삭제</a>
          </button>

        <!-- 요청과 댓글의 user 일치X = 모달 -->
        {% else %}
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            삭제
          </button>
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header bg-primary bg-opacity-25">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">삭제 오류</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  본인이 작성한 댓글만 삭제할 수 있습니다.
                </div>
              </div>
            </div>
          </div>
        {% endif %}

      </div>
    </div>
    <hr>
    {% empty %}
    <p>no comments</p>
  {% endfor %}
  </div>

  {% comment %} 댓글 입력 폼 {% endcomment %}
  {% if request.user.is_authenticated %}
  <form action="{% url 'articles:comment_create' article.pk %}" method="POST" class="mt-5">
    {% bootstrap_form comment_form layout="inline" %}
    {% csrf_token %}
    <div class="d-flex justify-content-end mt-3">
      {% comment %} 댓글_등록 {% endcomment %}
      {% bootstrap_button button_type="submit" content="등록" button_class="btn-primary" %}
    </div>
  </form>
  {% endif %}


  {% comment %} 버튼 {% endcomment %}
  <hr class="mt-5">
  <div class="d-flex justify-content-end">
    <button class="btn btn-secondary">
      <a href="{% url 'articles:index' %}" class="text-white text-decoration-none">
        메인
      </a>
    </button>
    <button class="btn btn-primary mx-1">
      <a href="{% url 'articles:update' article.pk %}" class="text-white text-decoration-none">
        수정
      </a>
    </button>
    <button class="btn btn-danger">
      <a href="{% url 'articles:delete' article.pk %}" class="text-white text-decoration-none">
        삭제
      </a>
    </button>
  </div>

{% endblock body %}

{% block script %}
  <script></script>
{% endblock script %}

djangoCRUD14/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>글 목록</h1>

  <table class="table mt-5">
    <thead class="table-dark">
      <tr>
        <th>글 번호</th>
        <th>제목</th>
        <th>작성자</th>
        <th>생성 일자</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
        <tr>
          <td>{{ article.pk }}</td>
          <td>
            <a href="{% url 'articles:detail' article.pk %}">
              {{ article.title }}</a>
          </td>
          <td>{{ article.user }}</td>
          <td>{{ article.created_at }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <button class="btn btn-primary mt-5">
    <a href="{% url 'articles:create' %}" class="text-white text-decoration-none">
      글 작성
    </a>
  </button>
{% endblock body %}

djangoCRUD14/articles/templates/articles/search.html
{% extends 'base.html' %}

{% block body %}
  <h1>검색 결과</h1>

  <table class="table mt-5">
    <thead class="table-success">
      <tr>
        <th>글 번호</th>
        <th>제목</th>
        <th>작성자</th>
        <th>생성 일자</th>
      </tr>
    </thead>
    <tbody>
      {% for page in page_obj %}
        <tr>
          <td>{{ page.pk }}</td>
          <td>
            <a href="{% url 'articles:detail' page.pk %}">
              {{ page.title }}</a>
          </td>
          <td>{{ page.user }}</td>
          <td>{{ page.created_at }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% comment %} 페이지네이션 {% endcomment %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for p_range in page_range %} 
      <li class="page-item">
        <a class="page-link" href="?page={{ p_range }}">{{ p_range }}</a>
      </li>
      {% endfor %}
    </ul>
  </nav>

  {% comment %} 검색창 {% endcomment %}
  <form class="d-flex my-5" role="search" action="{% url 'articles:search' %}" method="GET">
    <div class="col-2 me-2">
      <select class="form-select" name="search_1" placeholder={{ search_1 }}>
        <option value="title">제목</option>
        <option value="content">내용</option>
        <option value="username">작성자</option>
      </select>
    </div>
    <input class="form-control me-2" type="search" placeholder={{ search_2 }} name="search_2" required>
    <button class="btn btn-outline-primary" type="submit">search</button>
  </form>

{% endblock body %}

djangoCRUD14/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>update</h1>
  <form action="" method="POST">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" value="OK">
  </form>
{% endblock body %}